

#database
spring:
  datasource:
    url: jdbc:mysql://120.77.252.112:3306/db_user?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

service:
  name: user-thrift-service
  port: 7911