server:
  port: 8081
  userEdge:
    port: 8080
    ip: 192.168.0.108
dubbo:
  application:
    name: course-service
  registry:
    address: zookeeper://120.77.252.112:2181
  consumer:
    timeout: 5000

