#database
spring:
  datasource:
    url: jdbc:mysql://120.77.252.112:3306/db_user?serverTimezone=GMT%2B8
    username: root
    password: gexiao
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.77.252.112
    port: 6379

thrift:
  user:
    ip: 192.168.2.31
    port: 7911
  message:
    ip: 192.168.2.31
    port: 9090
server:
  port: 8082
  name: user-edge-service
